### ISSUE TITLE
Only first indented bullet gets new style

### ISSUE THREAD

**Issue by seanhagen** [pondersson/org-bulletproof#4]
My configuration for `orb-bulletproof`:

``` elisp
(use-package org-bulletproof
  :after org
  :init
  (global-org-bulletproof-mode +1)
  :custom
  (org-bulletproof-unordered-cycle '("-" "+" "*" "•" "‣" "⁍" "›" "᛭" "ᛜ" "⃘" "∞" "∝" "⊜" "⊝" "⋇" "⋆")))
```

After evaluating that, I tried testing it out. Only the second level bullet changed though:
![image](https://github.com/pondersson/org-bulletproof/assets/444767/6849078b-624a-4f94-8395-e7ec36c2425f)

Am I missing something?

**Comment by pondersson** [comment]
This mode only handles the bullets built into Org mode, so it's limited to `-`, `+` and `*` for unordered lists. Any other bullets are basically ignored. If I use your value of `org-bulletproof-unordered-cycle` it ignores all the unsupported bullets and loops back around to the default bullet as expected:

```
- level one
  + level two
    * level three
      - level four
```

I think maybe you're getting the same result but there's some kind of styling that makes the `-` and `*` bullets look the same?

**Comment by seanhagen** [comment]
Alrighty, thanks!
